# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^.+\.min\.(js|css)$
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [commit]
        exclude: >
          (?x)^(
              (.*)/static|
              (.*)/vendors|
              ^.+\.html$|
              ^.+\.mjml$|
              package-lock.json|
              (.*)/img/lottiefiles|
              ^.+\.min\.(js|css)$
          )$
        additional_dependencies:
          - prettier@3.3.3
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.7.0
    hooks:
      - id: stylelint
        additional_dependencies:
          - "postcss-scss"
          - "stylelint@16.7.0"
          - "stylelint-config-standard-scss@13.1.0"
        exclude: >
          (?x)^(
              (.*)/static|
              (.*)/vendors|
              ^.+\.min\.(css)$
          )$
