# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt --quiet
            pip install coveralls
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
            flake8 --exclude=venv* --statistics --exit-zero
            coveralls
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: coverage.xml
